### ISSUE TITLE
Rozbiť/premenovať triedu?

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#100]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicTerminal.cs#L63-L71

Vačšina metód tejto triedy robí niečo s employee, ale názov triedy je všeobecný a hovorí niečo o nejakom termináli. V kontexte názvu triedy by som asi tejto metóde nerozumel, keby sa trieda premenovala, potom by to už bolo jasnejšie.

**Comment by qubo6** [comment]
trieda je premenovaná a upravená jej funkcionalita
