### ISSUE TITLE
Príliš dlhá a ozátvorkovaná metóda, rozbiť na menšie metódky.

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#102]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Data/Repository/ConnectionManager.cs#L13

**Comment by Kazarr** [comment]
Rád si nechám poradiť ako to prerobiť lepšie. Zatiaľ je to to najkrajšie čo sme napísali
