### ISSUE TITLE
Dalo by sa zapísať jedným príkazom a potom namiesto return dať =>

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#104]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Data/Repository/ConnectionManager.cs#L47-L50

**Comment by Kazarr** [comment]
nechám si poradiť asi od aďa. Ten je zaťažený na písanie všetkého do jedného riadku.
