### ISSUE TITLE
Názov triedy mi nedáva zmysel

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#105]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Data/Model/DailyResult.cs#L9

V názve je result, čo mi evokuje nejaký výsledok niečoho, ale z properties to skôr chápem tak, že je to jeden záznam konkrétneho zamestnanca v dochádzke.

**Comment by misho048** [comment]
trieda premenovana
