### ISSUE TITLE
Takýto skript ideálne presunúť do súboru, nech sa prípadne dá zmeniť aj bez kompilácie programu

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#106]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Data/Repository/ManagerRepository.cs#L40

**Comment by Kazarr** [comment]
Všetky scripty môžeme presunúť do súboru ak je to nutné

**Comment by Kazarr** [comment]
Dobre do budúcnosti to už budem robiť do súboru :)
