### ISSUE TITLE
logika

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#47]
https://github.com/Kazarr/KrosDochadzka/blob/8dadec3bd3658cd7abcf83671b887cff02847da7/AttendanceTermianal/AttendanceSystem/frmPasswordChange.cs#L68-L70

toto by som hodil na logicku vrstvu

**Comment by Kazarr** [comment]
Je toto Ok ? Za mňa hej. Robí to view model namiesto view.

P.S.: ak toto čítaš a tiež si s tým v pohode zavri ma

**Comment by qubo6** [comment]
je to vo viewmodeli a vstupne parametre su nabindované
