### ISSUE TITLE
magic

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#52]
https://github.com/Kazarr/KrosDochadzka/blob/8dadec3bd3658cd7abcf83671b887cff02847da7/AttendanceTermianal/Logic/LogicTerminal.cs#L52
![image](https://user-images.githubusercontent.com/47741344/57617721-c3ef9480-7581-11e9-82c1-1ce55498a3df.png)
magicke cislo

**Comment by qubo6** [comment]
už neexistuje
