### ISSUE TITLE
Prázdne riadky, skrátený zápis, komentáre

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#59]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/TerminalViewModel.cs#L26-L36

- Metódy by sa dali zapísať cez skrátený zápis =>
- Chýbajú komentáre k public metódam
- Medzi definíciami metód dávame prázdny riadok
- Pridal by som regióny

**Comment by misho048** [comment]
hotovo
