### ISSUE TITLE
Zbytočná metóda?

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#61]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/TerminalViewModel.cs#L44-L48

Naozaj potrebujem na pridanie medzery k parametru metódu? A keď už tak, jej meno mi absolútne nič nepovie o tom čo metóda naozaj robí. Keď tak, pridal by som radšej nejakú extension metódu do string, napr. AddSpaceAtTheEnd

**Comment by misho048** [comment]
metoda vymazana
