### ISSUE TITLE
Repository radšej cez konštruktor alebo nejakú Factory triedu

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#62]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/TerminalViewModel.cs#L64

Akonáhle začnete pracovať so statickými triedami, vzniká riziko, že niekto začne používať repozitáre  kde sa mu zachce... a zbytočne sa previaže kód. Osobne by som to radšej spravil tak, že bude nejaká trieda RepositoryFactory, ktorá bude mať metódky vracajúce nové inštancie repozitárov, prípadne ešte ich môže vytvoriť len raz a držať si ich v pamäti. Vytvárali by sa iba pri prvom použití. Ideálne, keby sa táto factory trieda posielala do viewModelu cez konštruktor. RepositoryFactory by bola obyčajná trieda ktorá by len zabezpečovala vytváranie repozitárov. 

Ale teda keď už takto, tak aspoň pozor kde všade to voláte, aby nebolo milión miest ...

**Comment by Kazarr** [comment]
opravoval som v rámci [https://github.com/Kazarr/KrosDochadzka/issues/107](url)
Neviem či je to dobre podľa textu vyššie. Prerobil som to tak že teraz repositáre sú len v logike a vytvoria sa pri konštruktore logiky, tzn. pri spustení programu. Za mňa hotovo. 
P.S.: ak si aj ty čo toto čítaš s tým v pohode tak toto uzavri
