### ISSUE TITLE
Názov metódy

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#63]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/TerminalViewModel.cs#L60

Na začiatku by sa hodilo sloveso, napr. Is
Parameter mi tiež nehovorí nič, nie je samopopisný ..., input, to je priveľmi všeobecné

**Comment by Kazarr** [comment]
Možno vyriešil komentár ? Nevieem....

**Comment by qubo6** [comment]
upravené, bola tam jedna zbytočná metoda na forme, už používam len tú z viewmodelu
