### ISSUE TITLE
3x return, už sa strácam ...

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#64]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/TerminalViewModel.cs#L60

Nie je dobré v metódach používať viacnásobné returny. V takejto metódke by sa to dalo ešte odpustiť, ale akonáhle by tam ešte pribudol ďalší kód, už by to bolo neprehľadné ... kde všade sa vlastne dá vystúpiť z metódy? Radšej si na začiatku vytvoriť premennú ret typu bool a na konci ju vrátiť cez return.

**Comment by Kazarr** [comment]
Asi to už je vyriešené. Return je tam iba dva krát... asi stačí len uzavrieť. Nechám na teba

**Comment by qubo6** [comment]
vyriešené
