### ISSUE TITLE
Nastavovačky do viewModelu

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#65]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.cs#L117

Je tu kopec nastavovačiek a logiky, ktorá by mala byť skôr vo view modeli.

**Comment by Kazarr** [comment]
Za mňa je toto celkom ok. Nech sa qubo pozre očkom. on bude vedieť. Aj to riešil s dávidom

**Comment by qubo6** [comment]
vyriešené-upravené
