### ISSUE TITLE
Čo robí tento timer? Z názvu to nie je jasné.

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#69]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.cs#L22

Mená premenných by mali byť samopopisné.

**Comment by Kazarr** [comment]
Asi by som ho nazval terminalTime. Aby boli všetci spokojný

**Comment by qubo6** [comment]
premenovaný a aj druhý
