### ISSUE TITLE
Logika na formulári? Radšej nie ... presunúť niekde inde, nabindovať controlsy

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#70]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.cs#L25

**Comment by Kazarr** [comment]
Podľa mňa jedine keby sa tu nepoužíva Shared. ale niečo z connection managera.
