### ISSUE TITLE
Nabindovať

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#71]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.cs#L32

**Comment by Kazarr** [comment]
Nemám šajnu ako. (teda mám ale neviem ako to urobiť... viď prednáška) Rád sa prídem pozrieť ako sa to bude robiť.
