### ISSUE TITLE
NIe je lepšie použiť komponentu, ktorá pracuje s číslami?

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#73]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.cs#L123

**Comment by Kazarr** [comment]
Návrh: použiť numericTextBox ako mal kubo berthoty v jeho support dllke.

**Comment by qubo6** [comment]
puožitý numUpDown
