### ISSUE TITLE
Panely by som radšej pomenoval nech viem ktorý panel čo obsahuje

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#74]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.Designer.cs#L217

**Comment by qubo6** [comment]
panely služili hlavne kôli grafickému rozloženiu,
panel na ktorom su buttony a txtBox už je pomenovaný
