### ISSUE TITLE
;? prečo? nech aj dizajnér ma v názve dačo normálne

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#75]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.Designer.cs#L280

**Comment by misho048** [comment]
Hlavicka terminalu bola skryta, ale premenovlai sme ju
