### ISSUE TITLE
Skúste si zmeniť DPI a zobrazte si formuláre

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#76]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/AttendanceTermianal/frmTerminal.Designer.cs#L257-L263

Je lepšie používať dockovanie, napr. hlavný panel by mohol mať Fill a keď tam chcete nejaké odsadenie zo strán, použiť Padding/Margins

**Comment by Kazarr** [comment]
za mňa neriešiť teraz.
P.S.: ani za davida  :)

**Comment by Kazarr** [comment]
V tomto zadaní nebudeme riešiť. Uzatváram
