### ISSUE TITLE
Porušený Single responsibility principle

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#77]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicSystem.cs#L14

Trieda by mala byť zodpovedná len za jednu vec, za jeden súbor problémov. Táto trieda rieši všeho všudy, treba rozbiť na menšie servisy. Ani z názvu triedy nechápem, o čo ide a jediné, čo sa dozviem je to, že je to nejaká logická vrstva. Treba vymyslieť vhodné názvy a takéto pomocné logické triedy nazývať napr. Service.

**Comment by misho048** [comment]
táto trieda by mala reprezentovať logicku vrstvu na "AttendaceSystem" , obsahuje len metódy ktoré používa tato DLLka, mal by som teda rozbiť po jednotlivých formoch, aby každý form mal vlastný logic ?

**Comment by Kazarr** [comment]
V tomto zadaní už nebudeme riešiť. Uzatváram
