### ISSUE TITLE
TotalTimeWorked sa prečo nastavuje takto zvonka keď ju viem zrátať priamo v triede DaySummary?

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#79]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicSystem.cs#L96

**Comment by misho048** [comment]
DaySummary je Model, nechcel by som tam dávať  logiku, alebo ako si to myslel ?

**Comment by Kazarr** [comment]
Peťo je s tým už v pohode :)  ❤️
