### ISSUE TITLE
Metóda začína slovesom Set, ale v skutočnosti vracia novú inštanciu ... takže čo robí? Nastavuje? Vytvára? Premenovať ...

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#92]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicTerminal.cs#L16

A neviem, či by tu vôbec takáto funkcia mala byť ...

**Comment by misho048** [comment]
kod refaktorovany, metoda neexistuje
