### ISSUE TITLE
Musí tu byť kontrola na null? Nestačí mi vrátiť bool?

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#93]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicTerminal.cs#L30

A metódu by som premenoval potom nejaký Exists

**Comment by misho048** [comment]
kod refaktorovany funkcia neexistuje
