### ISSUE TITLE
Dvakrát vytváram rovnaký objekt.

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#94]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicTerminal.cs#L32

SetDailyResult(id_employee, type) je volaná dvakrát ...

**Comment by qubo6** [comment]
SetDailyResult už neexistuje- bola nepotrebná
