### ISSUE TITLE
Aké okno?

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#95]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicTerminal.cs#L43

**Comment by qubo6** [comment]
ak zamestnanec prišiel a odišiel z práce viac krát, tak "Okno" som považoval za časový priestor medzi prvým odchodom a následným príchodom
aktualne to obhospodaruje iná funkcia
