### ISSUE TITLE
Čo je to BlankSpace? Z názvu nechápem, o čo ide ...

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#96]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicTerminal.cs#L47

**Comment by qubo6** [comment]
bolo to na zaplnenie prázdneho časového intervalu v prípade viacnásobného príchodu a odchodu
už to obhospodaruje funkcia ktorá vytvára nový záznam
