### ISSUE TITLE
Testovacia premenná?

### ISSUE THREAD

**Issue by KrosTransformers** [Kazarr/KrosDochadzka#97]
https://github.com/Kazarr/KrosDochadzka/blob/e174d3d6f7d8132cda281079e4ed7944513a8d9e/Logic/LogicTerminal.cs#L50

Premenná test je akože nejaký testovací kód alebo čo to je? Ničnehovoriaci názov ...

**Comment by qubo6** [comment]
vyriešené-bolo to nepotrebné
